name: Build Road to Web

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '14'

            - name: Install VuePress
              run: npm install -g vuepress

            - name: Install Dependencies
              run: npm ci

            - name: Build VuePress site
              run: npm run docs:build

            - name: Deploy
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: gh-pages
                  FOLDER: docs/.vuepress/dist
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
